[package]
name = "components"
version = "0.1.0"
edition = "2021"

[dependencies]
web-component = { version = "0.1.11", features = ["web"] }
dioxus = { version = "0.6.3", features = ["web", "router"] }
